
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CADENA COMA DATE DOSPUNTOS EMAIL ID LLAVE_DER LLAVE_IZQ MOVIE_ID NAME NUMBERLONG OID TEXTjson : LLAVE_IZQ elementos LLAVE_DERelementos : par COMA elementoselementos : parpar : NAME DOSPUNTOS CADENApar : EMAIL DOSPUNTOS CADENApar : MOVIE_ID DOSPUNTOS objetopar : TEXT DOSPUNTOS CADENApar : DATE DOSPUNTOS objetopar : CADENA DOSPUNTOS objetopar : CADENA DOSPUNTOS CADENAobjeto : LLAVE_IZQ par LLAVE_DERobjeto : LLAVE_IZQ OID DOSPUNTOS CADENA LLAVE_DERobjeto : LLAVE_IZQ DATE DOSPUNTOS LLAVE_IZQ NUMBERLONG DOSPUNTOS CADENA LLAVE_DER LLAVE_DER'
    
_lr_action_items = {'LLAVE_IZQ':([0,14,16,18,33,],[2,23,23,23,35,]),'$end':([1,11,],[0,-1,]),'NAME':([2,12,23,35,],[5,5,5,5,]),'EMAIL':([2,12,23,35,],[7,7,7,7,]),'MOVIE_ID':([2,12,23,35,],[8,8,8,8,]),'TEXT':([2,12,23,35,],[9,9,9,9,]),'DATE':([2,12,23,35,],[10,10,30,30,]),'CADENA':([2,12,13,14,15,17,23,32,35,38,],[6,6,20,21,24,26,6,34,6,39,]),'LLAVE_DER':([3,4,19,20,21,22,24,25,26,27,28,31,34,36,39,40,41,],[11,-3,-2,-4,-10,-9,-5,-6,-7,-8,31,-11,36,-12,40,41,-13,]),'COMA':([4,20,21,22,24,25,26,27,31,36,41,],[12,-4,-10,-9,-5,-6,-7,-8,-11,-12,-13,]),'DOSPUNTOS':([5,6,7,8,9,10,29,30,37,],[13,14,15,16,17,18,32,33,38,]),'OID':([23,35,],[29,29,]),'NUMBERLONG':([35,],[37,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'json':([0,],[1,]),'elementos':([2,12,],[3,19,]),'par':([2,12,23,35,],[4,4,28,28,]),'objeto':([14,16,18,33,],[22,25,27,27,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> json","S'",1,None,None,None),
  ('json -> LLAVE_IZQ elementos LLAVE_DER','json',3,'p_json','yacc.py',6),
  ('elementos -> par COMA elementos','elementos',3,'p_elementos_1','yacc.py',10),
  ('elementos -> par','elementos',1,'p_elementos_2','yacc.py',14),
  ('par -> NAME DOSPUNTOS CADENA','par',3,'p_par_name','yacc.py',22),
  ('par -> EMAIL DOSPUNTOS CADENA','par',3,'p_par_email','yacc.py',26),
  ('par -> MOVIE_ID DOSPUNTOS objeto','par',3,'p_par_movie_id','yacc.py',30),
  ('par -> TEXT DOSPUNTOS CADENA','par',3,'p_par_text','yacc.py',34),
  ('par -> DATE DOSPUNTOS objeto','par',3,'p_par_date','yacc.py',38),
  ('par -> CADENA DOSPUNTOS objeto','par',3,'p_par_id','yacc.py',42),
  ('par -> CADENA DOSPUNTOS CADENA','par',3,'p_par_value','yacc.py',46),
  ('objeto -> LLAVE_IZQ par LLAVE_DER','objeto',3,'p_objeto_1','yacc.py',50),
  ('objeto -> LLAVE_IZQ OID DOSPUNTOS CADENA LLAVE_DER','objeto',5,'p_objeto_2','yacc.py',54),
  ('objeto -> LLAVE_IZQ DATE DOSPUNTOS LLAVE_IZQ NUMBERLONG DOSPUNTOS CADENA LLAVE_DER LLAVE_DER','objeto',9,'p_objeto_3','yacc.py',58),
]
