
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'body body_end h1 h1_end head head_end html html_end p p_end texto title title_endHTML : html CONTENT html_endCONTENT : HEADER BODYHEADER : head TITLE head_endTITLE : title TEXTO title_endBODY : body H1 PARAGRAPH body_endH1 : h1 TEXTO h1_endPARAGRAPH : p TEXTO p_end PARAGRAPHPARAGRAPH : TEXTO : textoTEXTO : '
    
_lr_action_items = {'html':([0,],[2,]),'$end':([1,6,],[0,-1,]),'head':([2,],[5,]),'html_end':([3,7,20,],[6,-2,-5,]),'body':([4,13,],[8,-3,]),'title':([5,],[10,]),'h1':([8,],[12,]),'head_end':([9,19,],[13,-4,]),'texto':([10,12,17,],[15,15,15,]),'title_end':([10,14,15,],[-10,19,-9,]),'p':([11,22,23,],[17,-6,17,]),'body_end':([11,16,22,23,24,],[-8,20,-6,-8,-7,]),'h1_end':([12,15,18,],[-10,-9,22,]),'p_end':([15,17,21,],[-9,-10,23,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'HTML':([0,],[1,]),'CONTENT':([2,],[3,]),'HEADER':([2,],[4,]),'BODY':([4,],[7,]),'TITLE':([5,],[9,]),'H1':([8,],[11,]),'TEXTO':([10,12,17,],[14,18,21,]),'PARAGRAPH':([11,23,],[16,24,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> HTML","S'",1,None,None,None),
  ('HTML -> html CONTENT html_end','HTML',3,'p_html','main2.py',5),
  ('CONTENT -> HEADER BODY','CONTENT',2,'p_content','main2.py',10),
  ('HEADER -> head TITLE head_end','HEADER',3,'p_header','main2.py',15),
  ('TITLE -> title TEXTO title_end','TITLE',3,'p_title','main2.py',20),
  ('BODY -> body H1 PARAGRAPH body_end','BODY',4,'p_body','main2.py',24),
  ('H1 -> h1 TEXTO h1_end','H1',3,'p_h1','main2.py',29),
  ('PARAGRAPH -> p TEXTO p_end PARAGRAPH','PARAGRAPH',4,'p_paragraph','main2.py',35),
  ('PARAGRAPH -> <empty>','PARAGRAPH',0,'p_paragraph_2','main2.py',41),
  ('TEXTO -> texto','TEXTO',1,'p_text','main2.py',47),
  ('TEXTO -> <empty>','TEXTO',0,'p_text1','main2.py',52),
]
